# Generated by Django 4.2 on 2024-01-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('timestamp', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
