# Generated by Django 4.2 on 2024-01-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='group_name',
            field=models.CharField(default='asdF', max_length=100),
            preserve_default=False,
        ),
    ]
