# Generated by Django 4.2 on 2024-01-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_message_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='agent',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='user_id',
            field=models.IntegerField(unique=True),
        ),
    ]
