# Generated by Django 4.2 on 2024-01-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_message_agent_alter_message_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_by',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
