# Generated by Django 4.2 on 2024-01-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_alter_message_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
