# Generated by Django 4.2 on 2024-01-19 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_agent_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='name',
        ),
    ]
