# Generated by Django 4.2 on 2024-01-19 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_remove_agent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='hasAgent',
            field=models.BooleanField(default=False),
        ),
    ]
